name: Download SharePoint Excel

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Access Token
        id: token
        run: |
          RESPONSE=$(curl -s -X POST -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.GRAPH_CLIENT_ID }}" \
            -d "scope=https://graph.microsoft.com/.default" \
            -d "client_secret=${{ secrets.GRAPH_CLIENT_SECRET }}" \
            -d "grant_type=client_credentials" \
            "https://login.microsoftonline.com/${{ secrets.GRAPH_TENANT_ID }}/oauth2/v2.0/token")
          echo "token=$(echo $RESPONSE | jq -r '.access_token')" >> $GITHUB_OUTPUT

      - name: Download Excel File
        run: |
          curl -L -X GET \
            -H "Authorization: Bearer ${{ steps.token.outputs.token }}" \
            -H "Accept: application/json" \
            "https://graph.microsoft.com/v1.0/sites/${{ secrets.SHAREPOINT_SITE_ID }}/drives/${{ secrets.SHAREPOINT_DRIVE_ID }}/items/${{ secrets.SHAREPOINT_ITEM_ID }}/content" \
            -o data/downloaded.xlsx

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/downloaded.xlsx
          git commit -m "Downloaded Excel from SharePoint"
          git push
